### ISSUE TITLE
Getting error while installing Qslim on ubuntu 15.04

### ISSUE THREAD

**Issue by anilkumar2444** [alecjacobson/qslim#2]
I am trying to install Qslim on ubuntu,
I have installed autoconf,fltk, libgfx, mixkit library successfully, however I got the following two warnings while adding libgfx, but libgfx added successfully.

1)
checking for FLTK library... no
checking for FLTK GL support... no

2)
checking GL/glext.h usability... no
checking GL/glext.h presence... yes
configure: WARNING: GL/glext.h: present but cannot be compiled
configure: WARNING: GL/glext.h: check for missing prerequisite headers?
configure: WARNING: GL/glext.h: proceeding with the preprocessor's result
configure: WARNING:     ## ------------------------------------ ##
configure: WARNING:     ## Report this to bug-autoconf@gnu.org. ##
configure: WARNING:     ## ------------------------------------ ##

After this I tried installing Qslim. Then I got this error

/home/anil/Desktop/qslim-2.1/tools/qslim/qvis.cxx:96: undefined reference to `MxGUI::status(char const*, ...)'
qvis.o: In function `main':
/home/anil/Desktop/qslim-2.1/tools/qslim/qvis.cxx:282: undefined reference to `MxGUI::add_toggle_menu(char const*, int, bool&, int)'
/home/anil/Desktop/qslim-2.1/tools/qslim/qvis.cxx:284: undefined reference to `MxGUI::add_toggle_menu(char const*, int, bool&, int)'
/home/anil/Desktop/qslim-2.1/tools/qslim/qvis.cxx:312: undefined reference to `MxGUI::run()'

It looks like it is failing to link Qslim to libgfx.
 It would be very grateful if somebody could help me with this. Thanks in advance.

**Comment by LAR-UFSC** [comment]
In this website there is a tutorial to compiling and run into the Mac ( new ones), I works similar to Ubuntu 16.04 (http://www.alecjacobson.com/weblog/?p=3244&cpage=1#comment-314203)

Just have to make small adjusts for Ubuntu.

sudo apt-get install fltk

libgfx:
Then, following the instructions in qslim-2.1/README.txt, I first compiled libgfx:

cd libgfx
./configure

The libpng support seems out of date and I don’t really need it so in raster-png.cxx I replaced:

//#ifdef HAVE_LIBPNG
#if false

memcopy was showing up undefined so I added the following include to raster.cxx:


#include <cstring>
Similarly there was a missing include in time.cxx:


#elif defined(HAVE_TIMES)
#include <sys/times.h>
Know, while inside libgfx I issue:


make -C src
mixkit
First travel inside mixkit and configure:


cd ../mixkit
./configure
Trying to make I got a bunch of errors of the form:


MxDynBlock.h:44:33: Error: 'resize' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
MxDynBlock.h:44:33: Error: note: declarations in dependent base 'MxBlock<MxStdModel*>' are not found by unqualified lookup
MxDynBlock.h:44:33: Error: note: use 'this->resize' instead
There’re at least two ways to fix this. You can add this-> everywhere gcc is tell you to: edit MxStack.h and MxDynBlock.h or you can add -fpermissive to the CXXFLAGS. This is awkwardly done not in mix-config but in ../libgfx/gfx-config. Where you can edit into something like:


CXXFLAGS = -g -O2  -I/Users/ajx/Downloads/qslim-2.1/libgfx/include -DHAVE_CONFIG_H $(WIN_FLAGS) -fpermissive
Alternatively you could have done this when configuring libgfx with:


cd ../libgfx
./configure CXXFLAGS='-fpermissive'
cd ../mixkit/
If you do it this way then you’ll get warnings instead of errors.

Now you can build with:

make -C src


Then: 

cd ../tools/qslim
make

It will be working.

**Comment by alecjacobson** [comment]
Thanks! It'd be great to eventually switch the build system to cmake...
